export const carConstants = {
    GET_CAR_REQUEST : 'GET_CAR_REQUEST',
    GET_CAR_SUCCESS : 'GET_CAR_SUCCESS',
    GET_CAR_FAILURE : 'GET_CAR_FAILURE',
    GET_CAR_DETAILS_BY_ID_REQUEST : 'GET_CAR_DETAILS_BY_ID_REQUEST',
    GET_CAR_DETAILS_BY_ID_SUCCESS : 'GET_CAR_DETAILS_BY_ID_SUCCESS',
    GET_CAR_DETAILS_BY_ID_FAILURE : 'GET_CAR_DETAILS_BY_ID_FAILURE'
}

export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS' ,
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  };
